 

 <td><a href="test.php"><b>Click Here To Go To HOME</b></a></td><br/>
 <marquee  behavior="scroll" direction="left" onmouseover="this.stop();" onmouseout="this.start();"><font color="red" size="3px"><b>This is Automatically Generated Question Paper.Select the generated question paper ,copy and paste the content in word.Please do necessary modifications before printing.</b></font></marquee>

<?php
session_start();
$check=$_SESSION['gen'];
if($check=='1')
{
//require("../exam/localmail.php");
 echo"<form action='forloop.php' method='POST'>";
echo"<center><input type='submit'name='laxmi' value='Generate another Question Paper'></center>";
echo"</form>";

date_default_timezone_set("Asia/Kolkata"); 
$t = date('d/m/Y h:i:s a', time());
echo"<html>";
echo"<head>";
echo"<title>";
echo"Generate Qustion paper";
echo"</title>";
echo"</head>";
echo"<body  height: 842px' width: '595px'>";
$host='localhost';
$username='root';
$password='';
$db='semester';
$connect=mysql_connect($host, $username, $password);
mysql_select_db("semester");
$count =array();
echo"<b> Answer any five  of the following questions 12 X 5 =60m </b><br/><br/><br/>";
for($i=1;$i<=8;$i++)
{
$hi=mysql_query( "SELECT count(1) FROM unit$i");
$row=mysql_fetch_array($hi);
$count[$i]=$row[0];
$c=rand(2,$count[$i]);
$query1=mysql_query( "SELECT q FROM  unit$i where qno='$c' ");
$row=mysql_fetch_array($query1);
echo"<font size='4.5px'>$i.$row[q] </font>";
echo"<br/>";  echo"<br/>";
}
echo"</body>";
echo"</html>";
/*$mail->Subject = "Automated Question paper Generation :$t" ;
$mail->Body = "<b>Hello Dear COE,<br/> Question paper had been generated by the user at time $t.<br/>Contact admin at :csemantraresults@gmail.com</b> ";

if(!$mail->Send())
    echo "Message was not sent <br />PHPMailer Error: " . $mail->ErrorInfo;
else
    echo "Message has been sent";
*/

}
else
{
echo "<script>location.href='http://localhost/JUMP/login/login.php'</script>";
}
?>